# Generated by Django 4.2.20 on 2025-04-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(default='Sin dirección', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('VISITADO', 'Visitado'), ('NO_INTERESADO', 'No interesado')], default='ACTIVO', max_length=15),
        ),
        migrations.AddField(
            model_name='store',
            name='systems',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
