# Generated by Django 4.2.20 on 2025-04-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_address_store_description_store_last_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('VISITADO', 'Visitado'), ('NO_INTERESADO', 'No interesado'), ('POR_VALIDAR', 'Por validar')], default='ACTIVO', max_length=15),
        ),
    ]
